//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_PR_13.AppAplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class PR13MOROZOVEntities : DbContext
    {
        private static PR13MOROZOVEntities _context;

        public PR13MOROZOVEntities()
            : base("name=PR13MOROZOVEntities")
        {
        }

        public static PR13MOROZOVEntities GetContext()
        {
            if (_context == null)
                _context = new PR13MOROZOVEntities();
            return _context;
        }
     
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sklad> Sklad { get; set; }
        public virtual DbSet<Strana> Strana { get; set; }
    }
}
